## Exercise 1: NumPy array Indexing/Slicing

#### 1.1) In this exercise, we will use the iris dataset. Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [4]:
import sys
import os
import numpy as np
import pandas as pd
sys.path.append("C:/Users/BeaBa/Documents/GitHub/si/src")

from si.data.dataset import Dataset
from si.io.csv_file import read_csv
from si.io.data_file import *

In [18]:
# Load the iris dataset
Path= "C:/Users/BeaBa/Documents/GitHub/si/datasets/iris/"
iris = read_csv(Path + "iris.csv", sep=",", label=True)
print("Shape of iris dataset:",iris.shape())
print(iris.X)
print("Features:", iris.features)
print("Label:", iris.label)

Shape of iris dataset: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]

#### 1.2) Select the penultimate independent variable. What is the dimension of the resulting array?

In [22]:
Penultimate= iris.X[:,-2]
print("Dimension:",Penultimate.shape[0])

Dimension: 150


####  1.3) Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable/feature?

In [29]:
# Select the last 10 samples
last_10_samples = iris.X[-10:, :]  

# Calculate the mean for each independent variable
means = last_10_samples.mean(axis=0)
features_names=data.features[:]
print(last_10_samples)
print("Means of the last 10 samples for each independent variable:")
for i in range(len(features_names)):
    print(f'{features_names[i]},:{means[i]}')

[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
Means of the last 10 samples for each independent variable:
feat_0,:6.450000000000001
feat_1,:3.0300000000000002
feat_2,:5.33
feat_3,:2.17


#### 1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables/features. How many samples do you obtain?

In [32]:
filtered_samples = iris.X[:, :-1][(iris.X[:, :-1] <= 6).all(axis=1)]
num_samples = filtered_samples.shape[0]
print("Number of samples with values ≤ 6 for all independent variables:", num_samples)

Number of samples with values ≤ 6 for all independent variables: 89


#### 1.5) Select all samples with a class/label different from 'Iris-setosa'. How many samples do you obtain?

In [36]:
Total_different_setosa = np.sum(iris.y != "Iris-setosa")
print("Number of samples:", Total_different_setosa)


Number of samples: 100
