In [25]:
import sys
import os
import numpy as np
import pandas as pd
sys.path.append("C:/Users/BeaBa/Documents/GitHub/si/src")

from si.data.dataset import Dataset
from si.io.csv_file import read_csv
from si.decomposition.pca import PCA as PCA
import matplotlib.pyplot as plt

In [8]:
Path= "C:/Users/BeaBa/Documents/GitHub/si/datasets/iris/"
iris = read_csv(Path + "iris.csv", sep=",", label=True)
iris.summary()

,feat_0,feat_1,feat_2,feat_3
mean,5.843333,3.054000,3.758667,1.198667
median,5.800000,3.000000,4.350000,1.300000
min,4.300000,2.000000,1.000000,0.100000
max,7.900000,4.400000,6.900000,2.500000
var,0.681122,0.186751,3.092425,0.578532


In [9]:
print("Label name:", iris.label)
print("Dataset has label?",iris.has_label())
print("Label classes:",iris.get_classes())
iris.shape()

Label name: class
Dataset has label? True
Label classes: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


(150, 4)

In [13]:
iris_pca = PCA(n_components=2)
iris_pca.fit(iris)

In [14]:
iris_pca.components

array([[ 0.36158968, -0.08226889,  0.85657211,  0.35884393],
       [-0.65653988, -0.72971237,  0.1757674 ,  0.07470647]])

In [15]:
iris_pca.explained_variance

array([0.92461621, 0.05301557])

In [16]:
iris_pca.get_covariance()


array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [17]:
iris_pca.mean


array([9.47390314e-17, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [19]:
# transformation of the dataset to the new principal components
iris_transformed = iris_pca.transform(iris)
iris_transformed.shape()

(150, 2)

In [20]:
iris_transformed.X

array([[-2.68420713, -0.32660731],
       [-2.71539062,  0.16955685],
       [-2.88981954,  0.13734561],
       [-2.7464372 ,  0.31112432],
       [-2.72859298, -0.33392456],
       [-2.27989736, -0.74778271],
       [-2.82089068,  0.08210451],
       [-2.62648199, -0.17040535],
       [-2.88795857,  0.57079803],
       [-2.67384469,  0.1066917 ],
       [-2.50652679, -0.65193501],
       [-2.61314272, -0.02152063],
       [-2.78743398,  0.22774019],
       [-3.22520045,  0.50327991],
       [-2.64354322, -1.1861949 ],
       [-2.38386932, -1.34475434],
       [-2.6225262 , -0.81808967],
       [-2.64832273, -0.31913667],
       [-2.19907796, -0.87924409],
       [-2.58734619, -0.52047364],
       [-2.3105317 , -0.39786782],
       [-2.54323491, -0.44003175],
       [-3.21585769, -0.14161557],
       [-2.30312854, -0.10552268],
       [-2.35617109,  0.03120959],
       [-2.50791723,  0.13905634],
       [-2.469056  , -0.13788731],
       [-2.56239095, -0.37468456],
       [-2.63982127,

In [21]:
for pc, explained_variance in zip(iris_transformed.features, iris_pca.explained_variance):
    print(f"Principal Component {pc}: Explained Variance: {explained_variance}")

Principal Component PC1: Explained Variance: 0.9246162071742681
Principal Component PC2: Explained Variance: 0.05301556785053509
